azure-pipelines-scheduled.yml
azure-pipelines.yml
build.gradle
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CsvWriterComponentImpl.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CsvWriterComponentImplTest.java

Added mutation tests and also in pipeline.
```
[ ] Yes
[x] No
```

Added mutation test

---

build.gradle
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CsvWriterComponentImplTest.java

Fix mutation test

---

build.gradle
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/MiExtractionServiceApplication.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/BlobExportService.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/impl/BlobExportServiceImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/smote/HealthService.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/MiExtractionServiceApplicationTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/service/impl/BlobExportServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/smoke/HealthServiceTest.java

Add smoke test

---

azure-pipelines-scheduled.yml
azure-pipelines.yml

Use prod as promotion environment

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CoreCaseDataExportBlobDataComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/impl/BlobExportServiceImpl.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CoreCaseDataExportBlobDataComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/service/impl/BlobExportServiceImplTest.java

Do not throw exception on no data to output scenarios

---

azure-pipelines.yml

Add trigger for ITHC branch

---

Jenkinsfile_CNP
build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/impl/BlobExportServiceImpl.java

Suppress warning for hasNext call

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/BlobSasMessageBuilderComponentImpl.java

Optimise string replace for tech debt

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CoreCaseDataFilterComponentImpl.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/CoreCaseDataFilterComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/test/helpers/TestConstants.java

Cover equal date conditions on filter

---

azure-pipelines-scheduled.yml
azure-pipelines.yml
charts/mi-extraction-service/values.yaml
src/main/resources/bootstrap.yaml

Remove archive password from chart and pipelines

---

azure-pipelines-scheduled.yml
azure-pipelines.yml

Fix promotion  build

---

.gitignore
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/mi/miextractionservice/test/CoreCaseDataExportTest.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/JsonlWriterComponent.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataCsvWriterComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataExportBlobDataComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataFilterComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataJsonlWriterComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataOutputFormatterComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataParserComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/domain/MiExtractionServiceConstants.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/impl/BlobExportServiceImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/wrapper/WriterWrapper.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataCsvWriterComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataExportBlobDataComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataFilterComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataJsonlWriterComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataOutputFormatterComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataParserComponentImplTest.java

Parse CCD as JSONL instead of CSV

---

.gitignore
src/functionalTest/java/uk/gov/hmcts/reform/mi/miextractionservice/test/CoreCaseDataExportTest.java
src/functionalTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/ArchiveComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataExportBlobDataComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/wrapper/FileWrapper.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataExportBlobDataComponentImplTest.java

Added flag to enable archiving and modified flow to support

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/ExportBlobDataComponentImpl.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/test/helpers/TestConstants.java

Use UTF-8 Charset when reading blob input

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/FilterComponent.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataFilterComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataWriteDataComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/notify/NotifyFilterComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/notify/NotifyWriteDataComponentImpl.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/corecasedata/CoreCaseDataWriteDataComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/notify/NotifyWriteDataComponentImplTest.java

Sonar improvements

---

src/functionalTest/java/uk/gov/hmcts/reform/mi/miextractionservice/data/TestConstants.java
src/functionalTest/java/uk/gov/hmcts/reform/mi/miextractionservice/test/ExportTest.java
src/functionalTest/resources/application.yaml
src/integrationTest/java/uk/gov/hmcts/reform/mi/miextractionservice/data/TestConstants.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/compression/CompressionComponent.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/compression/GzipCompressionComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/domain/Constants.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/export/ExportServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/archive/ArchiveComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/compression/GzipCompressionComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/service/export/ExportServiceImplTest.java

GZip Component

---

build.gradle
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/service/export/ExportServiceImplTest.java

Improved mutation test coverage

---

azure-pipelines-scheduled.yml
azure-pipelines.yml
charts/mi-extraction-service/requirements.yaml
charts/mi-extraction-service/requirements_template.yaml
charts/mi-extraction-service/values.yaml

Updated charts and pipeline to pass extraction-prs

---

charts/mi-extraction-service/values.stg.template.yaml

Disable Vault using Podidentity on stg

---

README.md

Updated extraction service readme

---

.gitignore
azure-pipelines.yml
build.gradle
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/MiExtractionServiceApplication.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/MiExtractionServiceApplicationTest.java

Added silent health check

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/MiExtractionServiceApplication.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/sftp/SftpExportComponentImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/SftpExportComponentImplTest.java

Add stacktrace

---

src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/sftp/SftpExportComponentImpl.java

Add traces for SFTP connection

---

.gitignore
build.gradle
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/impl/SftpExportComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/service/export/ExportServiceImplTest.java

Updated all dependabot dependencies

---

config/owasp/suppressions.xml

Suppress 2020-15250

---

build.gradle
config/owasp/suppressions.xml

Temporarily suppress irrelevant owasp checks

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/mi/miextractionservice/test/ExportTest.java
src/functionalTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/sftp/SftpExportComponent.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/component/sftp/SftpExportComponentImpl.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/domain/SourceProperties.java
src/main/java/uk/gov/hmcts/reform/mi/miextractionservice/service/export/ExportServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/component/sftp/SftpExportComponentImplTest.java
src/test/java/uk/gov/hmcts/reform/mi/miextractionservice/service/export/ExportServiceImplTest.java

Split sftp directory into sources

---

azure-pipelines.yml
src/main/resources/bootstrap.yaml

Add appinsights-instrumentationkey to bootstrap
